### ISSUE TITLE
[ Feedback ] Thanks

### ISSUE THREAD

**Issue by LemonatedCat** [Necres1977/cathook-PartyBypass#1]
At first i was pretty mad that someone open source'd the code due to my agreement with lmaobox, but you also upgraded the code significantly, incase you want a place in the Cathook Dev team, you'd probably need to contact us about Telegram, i'd also integrate this as a submodule since the code is out here now anyways, this repo would probably get forked to nullworks if so, sorry for this and thanks for this.

**Comment by LemonatedCat** [comment]
Basically: i didn't have alot of ASM knowledge so i had to find out a way to somehell bypass all steamid checks, patching the function itself did come to mind, but after a couple of crashes i gave up on it, so instead i patched all referencing parts, that's where the patch number comes from.

**Comment by LemonatedCat** [comment]
Thanks to your code i now understand assembly a bit better, thank you

**Comment by JustTNE** [comment]
+1
